### ISSUE TITLE
Label colours always seem to remain white

### ISSUE THREAD

**Issue by Oliver-Zimmerman** [g-apparence/spiderchart#2]
I am not sure if this is just an issue on my end but whenever I try to change the label colours they seem to remain white. This is an issue because my background is white.

Am I right in assuming that activeLabelColor is supposed to change this?

**Comment by g-apparence** [comment]
Hi, yes I think it's a bug. 
You can fix it and create a pull request about this if you want. I'll merge it.

**Comment by Oliver-Zimmerman** [comment]
Closed with: [https://github.com/g-apparence/spiderchart/pull/3](https://github.com/g-apparence/spiderchart/pull/3 )
